"""Add SafariImage model for multiple images

Revision ID: 0c52430b4ccc
Revises: 19f9cb06264e
Create Date: 2025-07-27 01:55:30.974979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c52430b4ccc'
down_revision = '19f9cb06264e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safari_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('safari_package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['safari_package_id'], ['safari_package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safari_image')
    # ### end Alembic commands ###
