"""Change image_url to images array

Revision ID: a380514f6d15
Revises: 2cabdc05e008
Create Date: 2025-07-27 00:47:09.457065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a380514f6d15'
down_revision = '2cabdc05e008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safari_package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safari_package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.drop_column('images')

    # ### end Alembic commands ###
