"""Add route_points field to SafariPackage

Revision ID: a8697f18436d
Revises: 880fa5bf85c3
Create Date: 2025-05-12 00:15:20.891387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8697f18436d'
down_revision = '880fa5bf85c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safari_package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_points', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safari_package', schema=None) as batch_op:
        batch_op.drop_column('route_points')

    # ### end Alembic commands ###
