"""Initial migration

Revision ID: f5bea9e1f99b
Revises: 
Create Date: 2025-07-27 01:25:47.874838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5bea9e1f99b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safari_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('price_range', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('route_map', sa.String(length=300), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('day_by_day', sa.Text(), nullable=True),
    sa.Column('rates', sa.Text(), nullable=True),
    sa.Column('inclusions', sa.Text(), nullable=True),
    sa.Column('getting_there', sa.Text(), nullable=True),
    sa.Column('offered_by', sa.String(length=200), nullable=True),
    sa.Column('tour_features', sa.Text(), nullable=True),
    sa.Column('route_details', sa.Text(), nullable=True),
    sa.Column('route_points', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=129), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('safari_package')
    # ### end Alembic commands ###
